shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/urls.py
from django.urls import path
from . import views
from .views import form_handler

app_name = 'myshop'

urlpatterns = [
    path('product_list/', views.product_catalog, name='product_list'),
    path('search/', views.search, name='search'),
    path('searchprod/', views.search_product, name='search_product'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('conditions/', views.conditions, name='conditions'),
    path('', views.random_products, name='home'),
    path('form/', form_handler, name='form_handler'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('<slug:category_slug>/', views.product_catalog,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>/', views.single_product, name='single-product'),
    path('review/<int:product_id>/<slug:slug>/', views.AddComments.as_view(), name='add_comments'),
    path('<int:id>/<slug:slug>/add_likes/', views.AddLike.as_view(), name='add_likes'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('accounts/login/', views.auth_login, name='login'),
    path('login2/', views.auth_login2, name='login2'),
    path('confirmation/<int:order_id>/', views.confirmation, name='confirmation'),
    path('checkout/', views.checkout, name='checkout'),
    path('register/', views.register, name='register'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/cart/models.py
from django.db import models

# Create your models here.

shop/cart/forms.py
from django import forms


PRODUCT_QUANTITY_CHOICES = [(i, str(i)) for i in range(1, 21)]


class CartAddProductForm(forms.Form):
    quantity = forms.TypedChoiceField(
                                choices=PRODUCT_QUANTITY_CHOICES,
                                coerce=int)
    update = forms.BooleanField(required=False,
                                initial=False,
                                widget=forms.HiddenInput)

shop/cart/views.py
from myshop.models import Product
from .cart import Cart
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404
from django.views.decorators.http import require_POST


@require_POST
def cart_add(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    quantity = int(request.POST.get('quantity', 1))
    update_quantity = request.POST.get('update', False)

    if update_quantity:
        cart.add(product=product, quantity=quantity, update_quantity=True)
    else:
        cart.add(product=product, quantity=quantity)

    return HttpResponseRedirect(f"{reverse('shop:product_list')}?added_to_cart={product.id}")


def cart_remove(request, product_id):
    cart = Cart(request)
    product = get_object_or_404(Product, id=product_id)
    cart.remove(product)
    return redirect('cart:cart_detail')


def cart_detail(request):
    cart = Cart(request)
    return render(request, 'cart/cart.html', {'cart': cart})

shop/cart/templates/cart/cart.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block content %}
    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>Корзина</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->
    <!--================Cart Area =================-->
    <section class="cart_area section_padding">
        <div class="container">
            <div class="cart_inner">
                <div class="table-responsive">
                    <table class="table">
                        <thead>
                        <tr>
                            <th scope="col">Товар</th>
                            <th scope="col">Цена</th>
                            <th scope="col">Количество</th>
                            <th scope="col">Итого</th>
                        </tr>
                        </thead>
                        <tbody>
                            {% for item in cart %}
                                {% with product=item.product %}
                                    <tr>
                                        <td>
                                            <div class="media">
                                                <div class="d-flex">
                                                    <img src="{{ product.image_1.url }}" alt="{{ product.name }}" />
                                                </div>
                                                <div class="media-body">
                                                    <p>{{ product.name }}</p>
                                                </div>
                                            </div>
                                        </td>
                                        <td>
                                            <h5>руб. {{ item.price }}</h5>
                                        </td>
                                        <td>
                                            {{ item.quantity }}
                                        </td>
                                        <td>
                                            <h5>руб. {{ item.total_price }}</h5>
                                        </td>
                                        <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
                                    </tr>
                                {% endwith %}
                            {% endfor %}
                            <tr class="bottom_button">
                                <td></td>
                                <td></td>
                                <td></td>
                                <td></td>
                            </tr>
                            <tr>
                                <td></td>
                                <td></td>
                                <td>
                                    <h5>Промежуточный итог</h5>
                                </td>
                                <td>
                                    <h5>руб. {{ cart.get_total_price }}</h5>
                                </td>
                            </tr>
                        </tbody>
                    </table>
                    <div class="checkout_btn_inner float-right">
                      <a class="btn_1" href="{% url 'myshop:product_list' %}">Продолжить покупки</a>
                      <a class="btn_1 checkout_btn_1" href="{% url 'orders:checkout' %}">Перейти к оформлению заказа</a>
                    </div>
              </div>
        </div>
  </section>
{% endblock %}

shop/cart/templates/cart/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
  Корзина покупок
{% endblock %}

{% block content %}
  <h1>Корзина покупок</h1>
  <table class="cart">
    <thead>
      <tr>
        <th>Картинка</th>
        <th>Товар</th>
        <th>Обновить кол-во</th>
        <th>Удалить</th>
        <th>Кол-во</th>
        <th>Цена за шт</th>
        <th>Общая стоимость</th>
      </tr>
    </thead>
    <tbody>
      {% for item in cart %}
        {% with product=item.product %}
          <tr>
            <td>
              <a href="{{ product.get_absolute_url }}">
                <img src="{% if product.image_1 %}{{ product.image_1.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
              </a>
            </td>
            <td>{{ product.name }}</td>
            <td>
              <form action="{% url 'cart:cart_add' product.id %}" method="post">
                {{ item.update_quantity_form.quantity }}
                {{ item.update_quantity_form.update }}
                <input type="submit" value="Обновить">
                {% csrf_token %}
              </form>
            </td>
            <td><a href="{% url 'cart:cart_remove' product.id %}">Удалить</a></td>
            <td>
              {{ item.quantity }}
            </td>
            <td class="num">руб. {{ item.price }}</td>
            <td class="num">руб. {{ item.total_price }}</td>
          </tr>
        {% endwith %}
      {% endfor %}
      <tr class="total">
        <td>Всего</td>
        <td colspan="4"></td>
        <td class="num">руб. {{ cart.get_total_price }}</td>
      </tr>
    </tbody>
  </table>
  <p class="text-right">
    <a href="{% url 'shop:product_list' %}" class="button light">В магазин</a>
    <a href="{% url 'orders:order_create' %}" class="button">Оформить заказ</a>
  </p>
{% endblock %}