shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/urls.py
from django.urls import path
from . import views
from .views import form_handler

app_name = 'myshop'

urlpatterns = [
    path('product_list/', views.product_catalog, name='product_list'),
    path('search/', views.search, name='search'),
    path('searchprod/', views.search_product, name='search_product'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('conditions/', views.conditions, name='conditions'),
    path('', views.random_products, name='home'),
    path('form/', form_handler, name='form_handler'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('<slug:category_slug>/', views.product_catalog,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>/', views.single_product, name='single-product'),
    path('review/<int:product_id>/<slug:slug>/', views.AddComments.as_view(), name='add_comments'),
    path('<int:id>/<slug:slug>/add_likes/', views.AddLike.as_view(), name='add_likes'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('accounts/login/', views.auth_login, name='login'),
    path('login2/', views.auth_login2, name='login2'),
    path('confirmation/<int:order_id>/', views.confirmation, name='confirmation'),
    path('checkout/', views.checkout, name='checkout'),
    path('register/', views.register, name='register'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/myshop/models.py
from django.db import models
from django.urls import reverse


class Subscription(models.Model):
    email = models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

    def __str__(self):
        return self.email


class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.message


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image_1 = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, verbose_name='Фото 1')
    image_2 = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, verbose_name='Фото 2')
    image_3 = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, verbose_name='Фото 3')
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:single_product', args=[self.id, self.slug])


class Comments(models.Model):
    '''Комментарий'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    title = models.ForeignKey(Product, verbose_name='Название товара', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.title}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    name = models.ForeignKey(Product, verbose_name='Название товара', on_delete=models.CASCADE)

shop/myshop/views.py
from cart.forms import CartAddProductForm
from .models import Category, Product, Likes, Subscription
from .form import CommentsForm
from .form import ContactForm
from .form import SubscribeForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.base import View


def search(request):
    query = request.GET.get('q')
    if query:
        results = Product.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )
    else:
        results = None

    return render(request, 'shop/search_results2.html', {'results': results, 'query': query})


def subscribe(request):
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            # Проверьте, существует ли уже такая подписка (по email)
            existing_subscription = Subscription.objects.filter(email=email).first()

            if not existing_subscription:
                # Если подписки с таким email нет, создайте новую
                subscription = Subscription(email=email)
                subscription.save()
            return render(request, 'shop/thank_you.html', {'email': email})
    else:
        form = SubscribeForm()

    return render(request, 'subscribe.html', {'form': form})


def contact(request):
    return render(request, 'shop/contact.html')


def about(request):
    return render(request, 'shop/about.html')


def blog(request):
    return render(request, 'shop/blog.html')


def index(request):
    return render(request, 'shop/index.html')


def conditions(request):
    return render(request, 'shop/conditions.html')


def random_products(request):
    # Извлекаем случайные 5 товаров с одной фотографией
    products = Product.objects.filter(image_1__isnull=False).order_by('?')[:6]

    # Находим минимальный товар по цене
    min_price_product = Product.objects.filter(image_1__isnull=False).exclude(price=None).order_by('price').first()

    context = {
        'products': products,
        'min_price_product': min_price_product,
    }
    return render(request, 'shop/index.html', context)


def form_handler(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form_data = form.save()
            return render(request, 'shop/success.html', {'form_data': form_data})
    else:
        form = ContactForm()
    return render(request, 'form.html', {'form': form})


def search_product(request):
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
    else:
        products = Product.objects.all()

    return render(request, 'shop/search_results.html', {'products': products, 'query': query})


def product_catalog1(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/product_list.html', {
        'category': category,
        'categories': categories,
        'products': products,
    })


def product_catalog(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    # Добавим пагинацию
    paginator = Paginator(products, 8)  # 10 товаров на страницу
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, показываем первую страницу
        products = paginator.page(1)
    except EmptyPage:
        # Если страница вне диапазона (например, если запрос ?page=9999), показываем последнюю страницу
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product_list.html', {
        'category': category,
        'categories': categories,
        'products': products,
    })


def single_product(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    context = {
        'product': product
    }
    return render(request, 'shop/single-product.html', context)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})


class AddComments(View):
    """добавление комментариев"""
    def post(self, request, product_id,):
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.title = Product.objects.get(id=product_id)
            comment.save()

        product = get_object_or_404(Product, id=product_id)
        return redirect('myshop:product_detail', id=product.id, slug=product.slug)


def get_client_ip(request):
    if 'HTTP_X_FORWARDED_FOR' in request.META:
        ip = request.META['HTTP_X_FORWARDED_FOR'].split(',')[0].strip()
    else:
        ip = request.META.get('REMOTE_ADDR', '')
    return ip


class AddLike(View):

    def get(self, request, id, slug):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client, name_id=id)
            return redirect('myshop:single-product', id=id, slug=slug)
        except:
            new_like = Likes()
            new_like.name = Product.objects.get(id=id)
            new_like.ip = ip_client
            new_like.pos_id = int(id)
            new_like.save()
            return redirect('myshop:single-product', id=id, slug=slug)

shop/myshop/templates/shop/base.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8" />
<title>{% block title %}Рукодельная Феерия{% endblock %}</title>
<link href="{% static "css/base.css" %}" rel="stylesheet">
</head>
<body>
<div id="header">
<a href="/" class="logo">Рукодельная Феерия</a>
</div>
<div id="subheader">
<div class="cart">Корзина пустая</div>
</div>
<div id="content">
{% block content %}{% endblock %}
</div>
</body>
</html>

shop/myshop/templates/shop/base2.html
<!-- base.html -->
{% load static %}
<!DOCTYPE html>
<html lang="zxx">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Ручные Сокровища</title>
    <link rel="shortcut icon" href="{% static 'img/favicon.png' %}"/>
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <!-- animate CSS -->
    <link rel="stylesheet" href="{% static 'css/animate.css' %}">
    <!-- owl carousel CSS -->
    <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/all.css' %}">
    <!-- flaticon CSS -->
    <link rel="stylesheet" href="{% static 'css/flaticon.css' %}">
    <link rel="stylesheet" href="{% static 'css/themify-icons.css' %}">
    <!-- font awesome CSS -->
    <link rel="stylesheet" href="{% static 'css/magnific-popup.css' %}">
    <!-- swiper CSS -->
    <link rel="stylesheet" href="{% static 'css/slick.css' %}">
    <!-- style CSS -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <style>
        #user-info {
            margin-left: 20px;
        }
    </style>
</head>
<body>
    <!--::header part start::-->
    <header class="main_menu home_menu">
        <div class="container">
            <div class="row align-items-center justify-content-center">
                <div class="col-lg-12">
                    <nav class="navbar navbar-expand-lg navbar-light">
                        <a class="navbar-brand" href="{% url 'myshop:home' %}"> <img src="{% static 'img/logo2.png' %}" alt="logo"> </a>
                        <button class="navbar-toggler" type="button" data-toggle="collapse"
                            data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent"
                            aria-expanded="false" aria-label="Toggle navigation">
                            <span class="menu_icon"><i class="fas fa-bars"></i></span>
                        </button>

                        <div class="collapse navbar-collapse main-menu-item" id="navbarSupportedContent">
                            <ul class="navbar-nav">
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'myshop:home' %}">Главная</a>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'myshop:about' %}">О магазине</a>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_1"
                                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        товары
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_1">
                                        <a class="dropdown-item" href="{% url 'myshop:product_list' %}"> Каталог товаров</a>
                                    </div>
                                </li>
                                <li class="nav-item dropdown">
                                    <a class="nav-link dropdown-toggle" href="blog.html" id="navbarDropdown_3"
                                        role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                        страницы
                                    </a>
                                    <div class="dropdown-menu" aria-labelledby="navbarDropdown_2">
                                        <a class="dropdown-item" href="{% url 'orders:login' %}">
                                            вход

                                        </a>
                                        <a class="dropdown-item" href="{% url 'orders:checkout' %}">оформление заказа</a>
                                        <a class="dropdown-item" href="{% url 'cart:cart_detail' %}">корзина</a>
                                    </div>
                                </li>
                                <li class="nav-item">
                                    <a class="nav-link" href="{% url 'myshop:contact' %}">Контакты</a>
                                </li>
                            </ul>
                        </div>
                        <div class="hearer_icon d-flex align-items-center">
                            <a id="search_1" href="javascript:void(0)"><i class="ti-search"></i></a>
                            <a href="{% url 'cart:cart_detail' %}">
                                <i class="flaticon-shopping-cart-black-shape"></i>
                            </a>
                            <!-- <div class="dropdown cart">
                                <a class="dropdown-toggle" href="cart" id="navbarDropdown3" role="button"
                                    data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    <i class="flaticon-shopping-cart-black-shape"></i>
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <div class="single_product">

                                    </div>
                                </div>
                            </div> -->
                        </div>
                        <div id="user-info">
                            {% if user.is_authenticated %}
                                <p>Привет, {{ user.username }}!</p>
                            {% else %}
                                <p>Добро пожаловать, гость!</p>
                            {% endif %}
                        </div>
                    </nav>
                </div>
            </div>
        </div>
        <div class="search_input" id="search_input_box">
            <div class="container">
                <form class="d-flex justify-content-between search-inner" method="GET" action="{% url 'myshop:search' %}">
                    <input type="text" class="form-control" id="search_input" name="q" placeholder="Искать здесь">
                    <button type="submit" class="btn">Search</button>
                    <span class="ti-close" id="close_search" title="Закрыть поиск"></span>
                </form>
            </div>
        </div>
    </header>
    <!-- Header part end-->

    <div class="content">
        {% block content %}{% endblock %}

  <!--::footer_part start::-->
  <footer class="footer_part">
        <div class="footer_iner section_bg">
            <div class="container">
                <div class="row justify-content-between align-items-center">
                    <div class="col-lg-8">
                        <div class="footer_menu">
                            <div class="footer_logo">
                                <a href="{% url 'myshop:home' %}"><img src="{% static 'img/logo2.png' %}" alt="#"></a>
                            </div>
                            <div class="footer_menu_item">
                                <a href="{% url 'myshop:home' %}">Главная</a>
                                <a href="{% url 'myshop:about' %}">О магазине</a>
                                <a href="{% url 'myshop:product_list' %}">Товары</a>
                                <a href="{% url 'myshop:contact' %}">Контакты</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4">
                        <div class="social_icon">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-instagram"></i></a>
                            <a href="#"><i class="fab fa-google-plus-g"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="copyright_part">
            <div class="container">
                <div class="row ">
                    <div class="col-lg-12">
                        <div class="copyright_text">
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
                            <P><!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. -->
Авторское право &copy;<script>document.write(new Date().getFullYear());</script> Все права защищены | Этот шаблон создан с помощью <i class="ti-heart" aria-hidden="true"></i> by <a href="https://colorlib.com" target="_blank">Colorlib</a>
<!-- Link back to Colorlib can't be removed. Template is licensed under CC BY 3.0. --></P>
                            <div class="copyright_link">
                                <a href="{% url 'myshop:conditions' %}">Правила и Условия</a>
                                <a href="{% url 'myshop:conditions' %}">Часто задаваемые вопросы</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </footer>
    <!--::footer_part end::-->
<script src="{% static 'js/jquery-1.12.1.min.js' %}"></script>
<script src="{% static 'js/popper.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.magnific-popup.js' %}"></script>
<script src="{% static 'js/swiper.min.js' %}"></script>
<script src="{% static 'js/mixitup.min.js' %}"></script>
<script src="{% static 'js/owl.carousel.min.js' %}"></script>
<script src="{% static 'js/jquery.nice-select.min.js' %}"></script>
<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/jquery.counterup.min.js' %}"></script>
<script src="{% static 'js/waypoints.min.js' %}"></script>
<script src="{% static 'js/contact.js' %}"></script>
<script src="{% static 'js/jquery.ajaxchimp.min.js' %}"></script>
<script src="{% static 'js/jquery.form.js' %}"></script>
<script src="{% static 'js/jquery.validate.min.js' %}"></script>
<script src="{% static 'js/mail-script.js' %}"></script>
<script src="{% static 'js/custom.js' %}"></script>
</body>
</html>

shop/myshop/templates/shop/contact.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block content %}
    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>контакты</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->

    <!-- ================ contact section start ================= -->
    <section class="contact-section section_padding">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <h2 class="contact-title">Связаться</h2>
                </div>
                <div class="col-lg-8">
                    <form class="form-contact contact_form" method="post" action="{% url 'myshop:form_handler' %}">
                        {% csrf_token %}
                        <div class="row">
                            <div class="col-12">
                                <div class="form-group">
                                    <textarea class="form-control w-100" name="message" id="message" cols="30" rows="9"
                                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Введите сообщение'"
                                        placeholder='Введите сообщение'></textarea>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input class="form-control" name="name" id="name" type="text"
                                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Введите ваше имя'"
                                        placeholder='Введите ваше имя'>
                                </div>
                            </div>
                            <div class="col-sm-6">
                                <div class="form-group">
                                    <input class="form-control" name="email" id="email" type="email"
                                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Введите email'"
                                        placeholder='Введите email'>
                                </div>
                            </div>
                            <div class="col-12">
                                <div class="form-group">
                                    <input class="form-control" name="subject" id="subject" type="text"
                                        onfocus="this.placeholder = ''" onblur="this.placeholder = 'Введите тему'"
                                        placeholder='Введите тему'>
                                </div>
                            </div>
                        </div>
                        <div class="form-group mt-3">
                            <button type="submit" class="btn_3 button-contactForm">Отправить сообщение</button>
                        </div>
                    </form>
                </div>
                <div class="col-lg-4">
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-home"></i></span>
                        <div class="media-body">
                            <h3>Санкт-Петербург, Россия.</h3>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-tablet"></i></span>
                        <div class="media-body">
                            <h3>7 (963) 30451 37</h3>
                        </div>
                    </div>
                    <div class="media contact-info">
                        <span class="contact-info__icon"><i class="ti-email"></i></span>
                        <div class media-body>
                            <h3>lelayshop@gmail.com</h3>
                            <p>Отправьте нам свой запрос в любое время!</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- ================ contact section end ================= -->
{% endblock %}

shop/myshop/templates/shop/single-product.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block content %}
    <!-- breadcrumb part start-->
    <section class="breadcrumb_part single_product_breadcrumb">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->
    <!--================Single Product Area =================-->
    <div class="product_image_area">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-12">
                    <div class="product_img_slide owl-carousel">
                        <div class="single_product_img">
                            <img src="{{ product.image_1.url }}" alt="{{ product.name }}" class="img-fluid">
                        </div>
                        <div class="single_product_img">
                            <img src="{{ product.image_2.url }}" alt="{{ product.name }}" class="img-fluid">
                        </div>
                        <div class="single_product_img">
                            <img src="{{ product.image_3.url }}" alt="{{ product.name }}" class="img-fluid">
                        </div>
                    </div>
                </div>
                <div>
                    <br>
                    <p>Понравилось: {{ product.likes_set.all.count }}</p>
                    <br>
                    <a href="{% url 'myshop:add_likes' product.id product.slug %}">Нравится</a>
                </div>
                <div class="col-lg-8">
                    <div class="single_product_text text-center">
                        <h3>{{ product.name }}</h3>
                        <p>{{ product.description }}</p>

                        <div class="card_area">
                            <div class="product_count_area">
                                <p>Количество</p>
                                <div class="product_count d-inline-block">
                                    <span class="product_count_item inumber-decrement"> <i class="ti-minus"></i></span>
                                    <input class="product_count_item input-number" type="text" value="1" min="0" max="10">
                                    <span class="product_count_item number-increment"> <i class="ti-plus"></i></span>
                                </div>
                                <p>руб.{{ product.price }}</p>
                            </div>
                            <div class="add_to_cart">
                                <form method="post" action="{% url 'cart:cart_add' product.id %}">
                                    {% csrf_token %}
                                    <button type="submit" class="btn_3">Добавить в корзину</button>
                                </form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <!--================End Single Product Area =================-->
    <!-- subscribe part here -->
    <section class="subscribe_part section_padding">
        <div class="container">
            <div class="row justify-content-center">
                <div class="col-lg-8">
                    <div class="subscribe_part_content">
                        <h2>Получайте акции и обновления!</h2>
                        <p></p>
                        <div class="subscribe_form">
                            <form method="post" action="{% url 'myshop:subscribe' %}">
                                {% csrf_token %}
                                <input type="email" name="email" placeholder="Введите ваш email">
                                <button type="submit" class="btn_1">Подписаться</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- subscribe part end -->
{% endblock %}

shop/myshop/templates/shop/thank_you.html
<!-- thank_you.html -->
<h2>Спасибо за подписку!</h2>
<p>Вы успешно подписались на наши обновления.</p>