shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/orders/urls.py
from django.urls import path
from . import views

app_name = 'orders'

urlpatterns = [
    path('accounts/login/', views.auth_login, name='login'),
    path('login2/', views.auth_login2, name='login2'),
    path('confirmation/<int:order_id>/', views.confirmation, name='confirmation'),
    path('checkout/', views.checkout, name='checkout'),
    path('register/', views.register, name='register'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/orders/models.py
from myshop.models import Product
from django.db import models
from django.contrib.auth.models import AbstractUser


class Order(models.Model):
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона', default='нет номера')
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    postal_code = models.CharField(max_length=20, verbose_name='Почтовый индекс')
    city = models.CharField(max_length=100, verbose_name='Город')
    created = models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')
    updated = models.DateTimeField(auto_now=True, verbose_name='Дата обновления')
    paid = models.BooleanField(default=False, verbose_name='Оплачен')

    class Meta:
        ordering = ('-created',)
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

    def __str__(self):
        return 'Order {}'.format(self.id)

    def get_total_cost(self):
        return sum(item.get_cost() for item in self.items.all())


class OrderItem(models.Model):
    order = models.ForeignKey(Order, related_name='items', on_delete=models.CASCADE)
    product = models.ForeignKey(Product, related_name='order_items', on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='Цена')
    quantity = models.PositiveIntegerField(default=1, verbose_name='Количество')

    def __str__(self):
        return '{}'.format(self.id)

    def get_cost(self):
        return self.price * self.quantity


class CustomUser(AbstractUser):
    groups = models.ManyToManyField('auth.Group', related_name='custom_user_set')
    user_permissions = models.ManyToManyField('auth.Permission', related_name='custom_user_set')
    first_name = models.CharField(max_length=50, verbose_name='Имя')
    last_name = models.CharField(max_length=50, verbose_name='Фамилия')
    phone_number = models.CharField(max_length=20, verbose_name='Номер телефона', default='нет номера')
    email = models.EmailField(verbose_name='Email')
    address = models.CharField(max_length=250, verbose_name='Адрес')
    postal_code = models.CharField(max_length=20, verbose_name='Почтовый индекс')
    city = models.CharField(max_length=100, verbose_name='Город')

    def __str__(self):
        return self.username

shop/orders/forms.py
from .models import CustomUser
from .models import Order
from django import forms
from django.contrib.auth.forms import UserCreationForm


class OrderCreateForm(forms.ModelForm):
    class Meta:
        model = Order
        fields = ['first_name', 'last_name', 'phone_number', 'email', 'address', 'postal_code', 'city']


class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = CustomUser
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name', 'phone_number', 'email',
                                                 'address', 'postal_code', 'city')

shop/orders/views.py
from django.shortcuts import get_object_or_404
from django.shortcuts import render, redirect
from django.contrib.auth import login, authenticate
from django.contrib.auth.decorators import login_required
from .forms import CustomUserCreationForm
from .forms import OrderCreateForm
from cart.cart import Cart
from .models import Order, OrderItem


def confirmation(request, order_id):
    order = get_object_or_404(Order, id=order_id)
    return render(request, 'orders/order/confirmation.html', {'order': order})


@login_required  # Декоратор, требующий аутентификации пользователя
def checkout(request, delivery_cost=300.00):
    cart = Cart(request)
    order = None

    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            # Создание заказа на основе данных формы
            order = form.save(commit=False)  # Создать заказ, но не сохранять его в базе данных
            if request.user.is_authenticated:
                # Если пользователь авторизован, свяжите заказ с этим пользователем
                order.user = request.user
            order.save()  # Теперь сохраните заказ в базе данных

            for item in cart:
                OrderItem.objects.create(order=order, product=item['product'], price=item['price'],
                                         quantity=item['quantity'])
            cart.clear()

            # Измените эту часть кода, чтобы передать объект заказа на страницу confirmation
            return redirect('orders:confirmation', order_id=order.id)
    else:
        if request.user.is_authenticated:
            # Если пользователь авторизован, предзаполните форму данными пользователя
            user = request.user
            form = OrderCreateForm(initial={
                'first_name': user.first_name,
                'last_name': user.last_name,
                'phone_number': user.phone_number,
                'email': user.email,
                'address': user.address,
                'postal_code': user.postal_code,
                'city': user.city,
            })
        else:
            form = OrderCreateForm()

    total_price = cart.get_total_price(delivery_cost=delivery_cost)
    return render(request, 'orders/order/checkout.html', {'cart': cart, 'form': form, 'delivery_cost': delivery_cost,
                                                          'total_price': total_price, 'order': order})


def auth_login2(request):
    if request.method == 'POST':
        username = request.POST.get('name')
        password = request.POST.get('password')
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('orders:checkout')
        else:
            pass
    return render(request, 'orders/order/checkout.html')


def order_create(request):
    cart = Cart(request)
    if request.method == 'POST':
        form = OrderCreateForm(request.POST)
        if form.is_valid():
            order = form.save()
            for item in cart:
                OrderItem.objects.create(order=order,
                                         product=item['product'],
                                         price=item['price'],
                                         quantity=item['quantity'])
            # очистка корзины
            cart.clear()
            return render(request, 'orders/order/created.html',
                          {'order': order})
    else:
        form = OrderCreateForm
    return render(request, 'orders/order/create.html',
                  {'cart': cart, 'form': form})


def auth_login(request):
    if request.method == 'POST':
        username = request.POST['name']
        password = request.POST['password']
        user = authenticate(request, username=username, password=password)
        if user is not None:
            login(request, user)
            return redirect('shop:product_list')
        else:
            pass
    return render(request, 'orders/order/login.html')


def register(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            user = form.save()
            login(request, user)
            return redirect('orders:login')
    else:
        form = CustomUserCreationForm()
    return render(request, 'orders/order/register.html', {'form': form})

shop/orders/templates/orders/order/checkout.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block content %}
    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>оформление заказа</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->

  <!--================Checkout Area =================-->
  <section class="checkout_area section_padding">
    <div class="container">
      <div class="returning_customer">
        <div class="check_title">
          <h2>
            Возвращающийся покупатель?
            <a href="#">Нажмите здесь, чтобы войти в систему</a>
          </h2>
        </div>
        <p>
          Если вы уже совершали покупки у нас раньше, пожалуйста, введите свои данные в
          поля ниже. Если вы новый клиент, пожалуйста, перейдите в раздел
          Выставления счетов и доставки.
        </p>
        <form method="post" action="{% url 'orders:login2' %}">
          {% csrf_token %}
          <div class="col-md-4 form-group p_star">
            <input type="text" class="form-control" id="name" name="name" value="" placeholder="Имя пользователя">
          </div>
          <div class="col-md-4 form-group p_star">
            <input type="password" class="form-control" id="password" name="password" value="" placeholder="Пароль">
          </div>
          <div class="col-md-6 form-group">
            <div class="creat_account d-flex align-items-center">
              <input type="checkbox" id="f-option" name="selector">
              <label for="f-option">Запомни меня</label>
            </div>
            <button type="submit" value="submit" class="btn_3">
              авторизоваться
            </button>
          </div>
        </form>
        <form class="row contact_form" method="post" novalidate="novalidate">
          {% csrf_token %}
          {{ form.as_p }}
          <div class="col-md-12 form-group">
            <button type="submit" class="btn_3">
              оформить заказ
            </button>
          </div>
        </form>
      </div>
      <div class="billing_details">
        <div class="row">
          <div class="col-lg-8">
          </div>
          <div class="col-lg-4">
            <div class="order_box">
              <h2>Ваш заказ</h2>
              <ul class="list">
                <li>
                  <a href="#">Товар
                    <span>Итого</span>
                  </a>
                </li>
                {% for item in cart %}
                <li>
                  <a href="#">{{ item.product.name }}
                    <span class="middle">x {{ item.quantity }}</span>
                    <span class="last">руб. {{ item.total_price }}</span>
                  </a>
                </li>
                {% endfor %}
              </ul>
              <ul class="list list_2">
                <li>
                  <a href="#">Промежуточный итог
                    <span>руб. {{ cart.get_total_price1 }}</span>
                  </a>
                </li>
                <li>
                  <a href="#">Доставка
                    <span>Единый тариф: руб. {{ delivery_cost }}</span>
                  </a>
                </li>
                <li>
                  <a href="#">Общая сумма
                    <span>руб. {{ total_price }}</span>
                  </a>
                </li>
              </ul>
          </div>
        </div>
      </div>
    </div>
  </section>
  <!--================End Checkout Area =================-->
{% endblock %}

shop/orders/templates/orders/order/confirmation.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block content %}

    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>подтверждение заказа</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->

    <!--================ confirmation part start =================-->
    <section class="confirmation_part section_padding">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="confirmation_tittle">
                        <span>Благодарю вас. Ваш заказ получен. Номер вашего заказа: {{ order.id }}. Ссылка на оплату будет выслана вам на email</span>
                    </div>
                </div>
            </div>
        </div>
    </section>
<!--================ confirmation part end =================-->

{% endblock %}

shop/orders/templates/orders/order/create.html
{% extends "shop/base.html" %}

{% block title %}Оформление заказа{% endblock %}

{% block content %}
    <h1>Оформление заказа</h1>
    <div class="order-info">
        <h3>Ваш заказ</h3>
        <ul>
            {% for item in cart %}
                <li>
                    {{ item.quantity }}x {{ item.product.name }}
                    <span>${{ item.total_price }}</span>
                </li>
            {% endfor %}
        </ul>
        <p>Итого: ${{ cart.get_total_price }}</p>
    </div>
    <form action="." method="post" class="order-form">
        {{ form.as_p }}
        <p><input type="submit" value="Разместить заказ"></p>
        {% csrf_token %}
    </form>
{% endblock %}

shop/orders/templates/orders/order/created.html
{% extends "shop/base.html" %}

{% block title %}Thank you{% endblock %}

{% block content %}
    <h1>Спасибо за покупку</h1>
    <p>Ваш заказ был успешно создан. Ваш номер заказа
        <strong>{{ order.id }}</strong>.</p>
{% endblock %}

shop/orders/templates/orders/order/login.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block content %}

    <!-- breadcrumb part start-->
    <section class="breadcrumb_part">
        <div class="container">
            <div class="row">
                <div class="col-lg-12">
                    <div class="breadcrumb_iner">
                        <h2>вход</h2>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- breadcrumb part end-->

    <!--================login_part Area =================-->
    <section class="login_part section_padding ">
        <div class="container">
            <div class="row align-items-center">
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_text text-center">
                        <div class="login_part_text_iner">
                            <h2>Новичок в нашем магазине?</h2>
                            <p></p>
                            <a href="{% url 'orders:register' %}" class="btn_3">Создать учетную запись</a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 col-md-6">
                    <div class="login_part_form">
                        <div class="login_part_form_iner">
                            <h3>С возвращением! <br>
                                Пожалуйста, войдите в систему прямо сейчас</h3>
                            <form method="post" action="{% url 'orders:login' %}">
                                {% csrf_token %}
                                <div class="col-md-12 form-group p_star">
                                    <input type="text" class="form-control" id="name" name="name" value="" placeholder="Имя пользователя">
                                </div>
                                <div class="col-md-12 form-group p_star">
                                    <input type="password" class="form-control" id="password" name="password" value="" placeholder="Пароль">
                                </div>
                                <div class="col-md-12 form-group">
                                    <div class="creat_account d-flex align-items-center">
                            <input type="checkbox" id="f-option" name="selector">
                                        <label for="f-option">Запомни меня</label>
                                    </div>
                                    <button type="submit" value="submit" class="btn_3">
                                        авторизоваться
                                    </button>
                                </div>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--================login_part end =================-->
{% endblock %}

shop/orders/templates/orders/order/register.html
{% extends 'shop/base2.html' %}
{% load static %}

{% block content %}
    <!-- Ваш существующий HTML-код для входа -->
    
    <div class="registration-form">
        <h2>Регистрация</h2>
        <form method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button type="submit">Зарегистрироваться</button>
        </form>
    </div>


    <!-- Дополнительный HTML-код, если необходимо -->

{% endblock %}