shop/cart/urls.py
from django.urls import path
from . import views

app_name = 'cart'


urlpatterns = [
    path('cart/', views.cart_detail, name='cart_detail'),
    path('add/<int:product_id>/', views.cart_add, name='cart_add'),
    path('remove/<int:product_id>/', views.cart_remove, name='cart_remove'),
]

shop/myshop/urls.py
from django.urls import path
from . import views
from .views import form_handler

app_name = 'myshop'

urlpatterns = [
    path('product_list/', views.product_catalog, name='product_list'),
    path('search/', views.search, name='search'),
    path('searchprod/', views.search_product, name='search_product'),
    path('contact/', views.contact, name='contact'),
    path('about/', views.about, name='about'),
    path('conditions/', views.conditions, name='conditions'),
    path('', views.random_products, name='home'),
    path('form/', form_handler, name='form_handler'),
    path('subscribe/', views.subscribe, name='subscribe'),
    path('<slug:category_slug>/', views.product_catalog,
         name='product_list_by_category'
         ),
    path('<int:id>/<slug:slug>/', views.single_product, name='single-product'),
    path('review/<int:product_id>/<slug:slug>/', views.AddComments.as_view(), name='add_comments'),
    path('<int:id>/<slug:slug>/add_likes/', views.AddLike.as_view(), name='add_likes'),
]

shop/shop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('orders.urls', namespace='orders')),
    path('', include('cart.urls', namespace='cart')),
    path('', include('myshop.urls', namespace='shop')),

]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/myshop/models.py
from django.db import models
from django.urls import reverse


class Subscription(models.Model):
    email = models.EmailField(unique=True)
    subscribed_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name = 'Подписчик'
        verbose_name_plural = 'Подписчики'

    def __str__(self):
        return self.email


class ContactMessage(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField()
    subject = models.CharField(max_length=200)
    message = models.TextField()

    class Meta:
        verbose_name = 'Сообщение'
        verbose_name_plural = 'Сообщения'

    def __str__(self):
        return self.message


class Category(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:product_list_by_category', args=[self.slug])


class Product(models.Model):
    category = models.ForeignKey(Category,
                                 related_name='products',
                                 on_delete=models.CASCADE)

    name = models.CharField(max_length=150, db_index=True)
    slug = models.CharField(max_length=150, db_index=True, unique=True)
    image_1 = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, verbose_name='Фото 1')
    image_2 = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, verbose_name='Фото 2')
    image_3 = models.ImageField(upload_to='product/%Y/%m/%d', blank=True, verbose_name='Фото 3')
    description = models.TextField(max_length=1000, blank=True)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    quantity = models.PositiveIntegerField(default=0)
    available = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    uploaded = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'Товар'
        verbose_name_plural = 'Товары'
        index_together = (('id', 'slug'), )

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('myshop:single_product', args=[self.id, self.slug])


class Comments(models.Model):
    '''Комментарий'''
    email = models.EmailField()
    name = models.CharField('Имя', max_length=50)
    text_comments = models.TextField('Текст комментария', max_length=2000)
    title = models.ForeignKey(Product, verbose_name='Название товара', on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.name}, {self.title}'

    class Meta:
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'


class Likes(models.Model):
    '''лайки'''
    ip = models.CharField('IP-адрес', max_length=100)
    name = models.ForeignKey(Product, verbose_name='Название товара', on_delete=models.CASCADE)

shop/myshop/views.py
from cart.forms import CartAddProductForm
from .models import Category, Product, Likes, Subscription
from .form import CommentsForm
from .form import ContactForm
from .form import SubscribeForm
from django.shortcuts import get_object_or_404
from django.db.models import Q
from django.shortcuts import render, redirect
from django.core.paginator import Paginator, PageNotAnInteger, EmptyPage
from django.views.generic.base import View


def search(request):
    query = request.GET.get('q')
    if query:
        results = Product.objects.filter(
            Q(name__icontains=query) |
            Q(description__icontains=query)
        )
    else:
        results = None

    return render(request, 'shop/search_results2.html', {'results': results, 'query': query})


def subscribe(request):
    if request.method == 'POST':
        form = SubscribeForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            # Проверьте, существует ли уже такая подписка (по email)
            existing_subscription = Subscription.objects.filter(email=email).first()

            if not existing_subscription:
                # Если подписки с таким email нет, создайте новую
                subscription = Subscription(email=email)
                subscription.save()
            return render(request, 'shop/thank_you.html', {'email': email})
    else:
        form = SubscribeForm()

    return render(request, 'subscribe.html', {'form': form})


def contact(request):
    return render(request, 'shop/contact.html')


def about(request):
    return render(request, 'shop/about.html')


def blog(request):
    return render(request, 'shop/blog.html')


def index(request):
    return render(request, 'shop/index.html')


def conditions(request):
    return render(request, 'shop/conditions.html')


def random_products(request):
    # Извлекаем случайные 5 товаров с одной фотографией
    products = Product.objects.filter(image_1__isnull=False).order_by('?')[:6]

    # Находим минимальный товар по цене
    min_price_product = Product.objects.filter(image_1__isnull=False).exclude(price=None).order_by('price').first()

    context = {
        'products': products,
        'min_price_product': min_price_product,
    }
    return render(request, 'shop/index.html', context)


def form_handler(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            form_data = form.save()
            return render(request, 'shop/success.html', {'form_data': form_data})
    else:
        form = ContactForm()
    return render(request, 'form.html', {'form': form})


def search_product(request):
    query = request.GET.get('q')
    if query:
        products = Product.objects.filter(
            Q(name__icontains=query) | Q(description__icontains=query)
        )
    else:
        products = Product.objects.all()

    return render(request, 'shop/search_results.html', {'products': products, 'query': query})


def product_catalog1(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request, 'shop/product_list.html', {
        'category': category,
        'categories': categories,
        'products': products,
    })


def product_catalog(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)

    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    # Добавим пагинацию
    paginator = Paginator(products, 8)  # 10 товаров на страницу
    page = request.GET.get('page')

    try:
        products = paginator.page(page)
    except PageNotAnInteger:
        # Если страница не является целым числом, показываем первую страницу
        products = paginator.page(1)
    except EmptyPage:
        # Если страница вне диапазона (например, если запрос ?page=9999), показываем последнюю страницу
        products = paginator.page(paginator.num_pages)

    return render(request, 'shop/product_list.html', {
        'category': category,
        'categories': categories,
        'products': products,
    })


def single_product(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    context = {
        'product': product
    }
    return render(request, 'shop/single-product.html', context)


def product_list(request, category_slug=None):
    category = None
    categories = Category.objects.all()
    products = Product.objects.filter(available=True)
    if category_slug:
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)
    return render(request, 'shop/product/list.html',
                  {
                      'category': category,
                      'categories': categories,
                      'products': products
                  })


def product_detail(request, id, slug):
    product = get_object_or_404(Product,
                                id=id,
                                slug=slug,
                                available=True)
    cart_product_form = CartAddProductForm()
    return render(request, 'shop/product/detail.html', {'product': product,
                                                        'cart_product_form': cart_product_form})


class AddComments(View):
    """добавление комментариев"""
    def post(self, request, product_id,):
        form = CommentsForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.title = Product.objects.get(id=product_id)
            comment.save()

        product = get_object_or_404(Product, id=product_id)
        return redirect('myshop:product_detail', id=product.id, slug=product.slug)


def get_client_ip(request):
    if 'HTTP_X_FORWARDED_FOR' in request.META:
        ip = request.META['HTTP_X_FORWARDED_FOR'].split(',')[0].strip()
    else:
        ip = request.META.get('REMOTE_ADDR', '')
    return ip


class AddLike(View):

    def get(self, request, id, slug):
        ip_client = get_client_ip(request)
        try:
            lik = Likes.objects.get(ip=ip_client, name_id=id)
            return redirect('myshop:single-product', id=id, slug=slug)
        except:
            new_like = Likes()
            new_like.name = Product.objects.get(id=id)
            new_like.ip = ip_client
            new_like.pos_id = int(id)
            new_like.save()
            return redirect('myshop:single-product', id=id, slug=slug)

shop/myshop/templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}

{% block title %}
{{ product.name }}
{% endblock %}

{% block content %}
<div class="product-detail">
  {% if product.image_1 %}
    <img src="{{ product.image_1.url }}" alt="{{ product.name }} Image 1" >
  {% elif product.image %}
    <img src="{{ product.image.url }}" alt="{{ product.name }} Main Image">
  {% else %}
    <img src="{% static "img/no_image.png" %}" alt="No Image">
  {% endif %}

  {% if product.image_2 %}
    <img src="{{ product.image_2.url }}" alt="{{ product.name }} Image 2" >
  {% endif %}

  {% if product.image_3 %}
  <img src="{{ product.image_3.url }}" alt="{{ product.name }} Image 3" >
  {% endif %}

  <h1>{{ product.name }}</h1>
  <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
  <p class="price">руб. {{ product.price }}</p>
  <form action="{% url 'cart:cart_add' product.id %}" method="post">
    {{ cart_product_form }}
    {% csrf_token %}
    <input type="submit" value="Добавить в корзину">
  </form>
</div>
<div>
  <br>
  <p>Понравилось: {{ product.likes_set.all.count }}</p>
  <br>
  <a href="{% url 'myshop:add_likes' product.id product.slug %}">Нравится</a>
  <a href="{% url 'myshop:del_likes' product.id product.slug %}">Не нравится</a>
</div>
<div class="form-comment">
  <h3>Оставить комментарий</h3>
  <div>
    <form action="{% url 'myshop:add_comments' product.id %}" method="post">
      {% csrf_token %}
      <div>
        <label>Ваш комментарий</label>
        <textarea name="text_comments"></textarea>
      </div>
      <div>
        <label>Ваше имя *</label>
        <input type="text" name="name">
      </div>
      <div>
        <label>Ваш Email *</label>
        <input type="email" name="email">
      </div>
      <div><input type="submit"></div>
    </form>
  </div>
</div>
<div>
  {% for comment in product.comments_set.all %}
  <div class="view-comment">
    <h4>{{ comment.name }}</h4>
    <p>{{ comment.text_comments }}</p>
  </div>
  {% endfor %}
</div>
{% endblock %}

shop/myshop/templates/shop/product/list.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
{% if category %}{{ category.name }}{% else %}Товары{% endif %}
{% endblock %}
{% block content %}
<div id="sidebar">
<h3>Категория</h3>
<ul>
<li {% if not category %}class="selected"{% endif %}>
<a href="{% url 'shop:product_list' %}">Все</a>
</li>
{% for c in categories %}
<li {% if category.slug == c.slug %}class="selected" {% endif %}>
<a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
</li>
{% endfor %}
</ul>
</div>
<div id="main" class="product-list">
<h1>{% if category %}{{ category.name }}{% else %}Товар{% endif %}</h1>
{% for product in products %}
<div class="item">
    <a href="{{ product.get_absolute_url }}">
        {% if product.image_1 %}
            <img src="{{ product.image_1.url }}" alt="{{ product.name }} Image 1" >
        {% elif product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }} Main Image">
        {% else %}
            <img src="{% static 'img/no_image.png' %}" alt="No Image">
        {% endif %}
    </a>
    <a href="{{ product.get_absolute_url }}">{{ product.name }}</a>
    <br>
    руб. {{ product.price }}
    <br>
</div>
{% endfor %}
</div>
{% endblock %}